# Generated by Django 5.1.5 on 2025-01-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bod',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
